name: Build and deploy Node.js app to Azure Web App - gesundes-buero

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install and build frontend
      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Upload artifacts for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A0F6BD9B7E10491B86D54A683E57151D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CBF9D586D0F2449E8610D67CE7119ED2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DB1E097E0FAF4ED9B43DAA4544D4B998 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'gesundes-buero'
          slot-name: 'Production'
          package: ./backend


