name: Build and deploy Node.js app to Azure Web App - gesundes-buero

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies and build for frontend
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # Install dependencies for backend
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend
      
      # Upload built frontend for deployment
      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: ./frontend/dist

      # Zip backend for deployment
      - name: Zip backend files
        run: zip -r backend.zip ./
        working-directory: ./backend

      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-zip
          path: ./backend/backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
      
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A0F6BD9B7E10491B86D54A683E57151D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CBF9D586D0F2449E8610D67CE7119ED2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DB1E097E0FAF4ED9B43DAA4544D4B998 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'gesundes-buero'
          slot-name: 'Production'
          package: backend/backend.zip
